### ISSUE TITLE
タイムラインの設定で、タイムラインの大きさを「ちび」にすると設定ボタンがはみ出る

### ISSUE THREAD

**Issue by TaktstockJp** [uboar/missli#12]
環境
OS：Windows11
ブラウザ：FireFox 112.0.1
画面解像度：1920x1080
上記でウインドウを最大化した状態でMissLIを使用している時に発生

不具合の内容としてはタイトルの通りです。
大きさが「ちび」のタイムラインの右に別のタイムラインがあると、そのタイムラインの通知ボタンに設定ボタンが隠れてしまい、押しづらくなります。

**Comment by uboar** [comment]
ありがとうございます！

こちらでもUIがはみ出してしまうのを確認しました。修正させて頂きます。🙇

**Comment by uboar** [comment]
1.7.1で表示を調整しました。ちびでもはみ出さないと思います。

![image](https://user-images.githubusercontent.com/10250330/233775696-0aeb31b9-ce21-41e7-a4df-f504f9d9fc96.png)
