### ISSUE TITLE
チャンネルごとの色を反映

### ISSUE THREAD

**Issue by MinmiMin** [uboar/missli#13]
TL中のフォロー中チャンネルのノートが色つきになる本家の機能が便利なので、こちらでも実装されると嬉しいです。
チャンネルの色は`channels/show`で取得できるようなのでよろしくお願いします。

**Comment by uboar** [comment]
ありがとうございます！次回アップデートの際に機能追加させて頂きます。

**Comment by uboar** [comment]
1.7.4のアップデートで機能追加しました。
