### ISSUE TITLE
「チャンネル」タイムラインが追加できない

### ISSUE THREAD

**Issue by mimikun** [uboar/missli#14]
以下の画像のように、一瞬チャンネル一覧?が表示されるのですがすぐ「ホーム」に変わってしまいます

https://gyazo.com/32d13cf15ef0d727cceb678a655e209d

## 環境
- Windows 11 Version 22H2 (Build 22621.1928)
- Vivaldi 6.1.3035.111 (Stable channel) (64-bit)

**Comment by uboar** [comment]
ありがとうございます。
チャンネルタイムラインを追加する際にリストに表示されるチャンネルは、自分が「フォロー」しているチャンネルが対象になっていますので、まずは該当のチャンネルをフォローしてみて下さい。

（もしフォローしているのに表示されない！という場合、2023/7/3現在Misskey.ioのサーバーが不安定なので上手く取得出来ていない場合があります。別のサーバーで試してみて下さい）

**Comment by mimikun** [comment]
ありがとうございます。
現時点(2023年7月7日 0時56分)でこの問題は解決しているのでクローズします。
