### ISSUE TITLE
フォロー中のチャンネルだけでなくお気に入り中のチャンネルも追加できるようにしたい

### ISSUE THREAD

**Issue by TaktstockJp** [uboar/missli#19]
まず、不具合報告というよりは追加機能の要望(GitHubのラベルでいえばEnhancementにあたる)になることをお許しください。

現在、MissLIでカラムに追加できるチャンネルは、ユーザーがフォローしているもののみとなっています。
一方で、Misskeyでユーザーからチャンネルに行える操作は、フォローとお気に入りに分離されています。
チャンネルの流速によってはフォローするとホームが埋まってしまうため、お気に入りだけしてフォローしていないチャンネルがあるのですが、そういったチャンネルを直接カラムに追加できれば便利だと思った次第です。

**Comment by uboar** [comment]
ありがとうございます！次回のアップデートで実装します。

**Comment by uboar** [comment]
[1.8.0](https://github.com/uboar/missli/releases/tag/1.8.0)で実装しました。
