### ISSUE TITLE
ユーザー追加に失敗する

### ISSUE THREAD

**Issue by hiro-mi** [uboar/missli#5]
## 概要
MissLI初期状態からユーザーを追加することができません

## 環境
Google Chrome バージョン: 110.0.5481.177（Official Build） （64 ビット）
Windows 10 Pro 19045.2673

## 再現手順
1. https://uboar.github.io/missli/ を開く
2. 「設定」ボタンを押下する
3. 「ユーザーを追加する」欄にユーザーを入力し、「認証する」ボタンを押下する
4. 画面遷移し、「Offline. Service Worker @13.8.1」という画面に表示される

4.での遷移先URLは該当するインスタンス以下となります。
コンソールに以下のようなエラーが出ることがあります（1度確認したため記録がのこっていますが再現ができませんでした）

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'reduce')
    at ne.construct (sw.js:1:29163)
```

通常ウインドウとシークレットモードで同様の挙動をすることを確認しています。
また、https://uboar.github.io/missli/ のローカルストレージは消去しても同様の挙動を示します。
対象としたアカウント・インスタンスは@shioming@misskey.systems、@shioming@mk.shrimpia.networkとなります。

**Comment by uboar** [comment]
ありがとうございます！推測ですが、入力欄にアカウント名も含めて記載していませんか？
認証情報は大元のクライアントでログインしているアカウントに紐付くので、入力するのはインスタンスのURLのみになります。（例：シュリンピア帝国なら`[mk.shrimpia.network](mailto:shioming@mk.shrimpia.network)`と入力してください。

**Comment by uboar** [comment]
また、UIの表示が不親切なので、修正します。

**Comment by hiro-mi** [comment]
その通りでした。
ご指摘の通りで動作しました、ありがとうございました！

**Comment by uboar** [comment]
8748fe5：文言を修正しました。
