### ISSUE TITLE
めいすきー(Misskey v10)でログインできない

### ISSUE THREAD

**Issue by kazu0617** [uboar/missli#6]
https://misskey.m544.net で入ろうとした際にNot Foundになる。恐らくAPIの互換性がない。
https://meisskey.fediverse.observer/list から確認可能。
API: https://misskey.m544.net/api-doc (v10なので恐らくちゃんとしてる）

**Comment by uboar** [comment]
すみません、現在MiAuth認証しか対応出来ていないので、古い認証形式では連携出来ません！時間のある時に対応させて頂きます！

**Comment by uboar** [comment]
ひとまず、[1.3.4](https://github.com/uboar/missli/releases/tag/1.3.4)リリースでアクセストークンを直接入力して認証する方式に対応しました。v11のMisskey.devで動作を確認しています。
